### ISSUE TITLE
Negative unknown attempts

### ISSUE THREAD

**Issue by gonkergd** [Uproxide/practice-attempts#1]
![20240707171856_1](https://github.com/Uproxide/practice-attempts/assets/59105483/db7f732f-3221-4422-a01b-584315cd70d4)

**Comment by Uproxide** [comment]
this is not an issue with Practice Attempts.

**Comment by gonkergd** [comment]
Just asking, but how isnt it? What are negative attempts supposed to mean?

**Comment by gonkergd** [comment]
Oh this mod doesnt provide the attempts its betterinfo... sorry for interrupting, have a nice day.
